name: Tunein
description: A dynamically themed music player with built in casting support made with Flutter
version: 0.1.2


publish_to: "none"


environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  audioplayer:
    git:
      ref: master
      url: https://github.com/moda20/audioplayer
  path_provider: ^2.0.11
  flutter_reorderable_list: ^1.2.0
  rxdart: ^0.27.7
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.0.15
  media_notification:
    git:
      url: https://github.com/moda20/flutter_media_notification
      ref: master
  permission_handler: ^10.2.0
  get_it: ^7.2.0
  crypto: ^3.0.2
  uuid: ^3.0.7
  page_transition: "^1.1.5"
  flutter_custom_dialog: ^1.2.0
  fading_edge_scrollview: ^3.0.0
  string_similarity: ^2.0.0
  another_flushbar: ^1.12.29
  settings_ui: ^2.0.2
  #flutter_i18n: ^0.20.1
  marquee: ^2.2.3
  flutter_isolate: ^2.0.4
  dio: ^4.0.6
  dio_flutter_transformer2: ^4.0.1
  morpheus: ^1.2.2+1
  animations: ^2.0.7
  badges: ^2.0.3
  popup_menu: # this package is only updated on github but the update is not pushed to pub.dev
    git:
      url: https://github.com/chinabrant/popup_menu
      ref: master
  upnp:
    git:
      url: https://github.com/moda20/upnp.dart
      ref: master
  connectivity_plus: ^3.0.2
  flutter_file_meta_data:
    git:
      url: https://github.com/moda20/flutter_file_meta_data
      ref: master
  dart_ping: ^7.0.2
  preload_page_view:
    git:
      url: https://github.com/moda20/preload_page_view
      ref: 90bf545d49c79cb4980db3cf396e87a7e4b26f58
      publish_to: none
  toast: ^0.3.0
  expandable: ^5.0.1
  flutter_inner_drawer:
    git:
      url: https://github.com/bikcrum/flutter_inner_drawer
      ref: bugfix/type-casting
  url_launcher: ^6.1.7
  dart_tags: ^0.4.0
  autocomplete_textfield: ^1.7.3
  tunein_image_utils_plugin:
    git:
      url: https://github.com/moda20/tunein_image_utils_plugin
  media_gallery: ^0.1.5
  image_list: ^3.0.0
  extended_tabs: ^4.0.2
  external_path: ^1.0.3
  photo_gallery: ^1.1.1
  network_info_plus: ^3.0.1
  collection: ^1.16.0
  # ext_storage: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  assets:
    - images/
    - locale/
  fonts:
    - family: Boxicons
      fonts:
        - asset: fonts/boxicons.ttf
          weight: 400
    - family: Fontawesome
      fonts:
        - asset: fonts/fa.ttf
          weight: 400
    - family: LigatureSymbols
      fonts:
          - asset: fonts/LigatureSymbols-2.11.ttf
            weight: 400



  
  uses-material-design: true
